### ISSUE TITLE
generate_prior() problem

### ISSUE THREAD

**Issue by bhym** [frmunoz/ecolottery#11]
Using the latest developmental version, the `generate_prior()` function  fails with 

```error in prior[[length(prior) + 1]]: Index out of bounds```

Could the culprit be this line? 
https://github.com/frmunoz/ecolottery/blob/7b82c213d550ec18c4ccd0bfe6a23ba7d51e5493/pkg/R/coalesc_abc.R#L874

**Comment by frmunoz** [comment]
Could you provide the call of coalesc_abc that has generated this error (with information on input values)?

**Comment by bhym** [comment]
This is the call i am using
```
 coalesc_abc(arc.res, multi = "single",
                       filt.abc = NULL,
                       traits = NULL,
                       prop =F,
                       f.sumstats = f.sumstats, params = NULL,
                       theta.max = 100, nb.samp = 1000, tol = 0.01,
                       pkg = c("vegan","betapart"), method.abc = "neuralnet",
                       parallel = F)
```

where arc.res is the result of  `rrarefy()`, and f.sumstat is

```
f.sumstats <- function(tab) {
  rich <- apply(tab, 1, function(x) sum(x!=0))
  shan <- apply(tab, 1, function(x) vegan::diversity(x, index="shannon"))
  beta <- lapply(betapart::beta.pair.abund(tab),
                 function(x) rowMeans(as.matrix(x), na.rm=T))$beta.bray
  stats <- c(rich, shan, beta)
  names(stats) <- paste0(rep(c("rich", "shan", "beta"), each = 19), 1:19)
  return(stats)
}
```

**Comment by frmunoz** [comment]
Because arc.res is a species-by-site table, you should use the option multi = "tab" instead of multi = "single". Apart from this point, I have corrected a bug that appeared when generating the prior for theta. Please use the last version of the package on Github.
Do not hesitate to request any further assistance if needed.
