### ISSUE TITLE
Examples in `coalesc()` used theta with custom pool

### ISSUE THREAD

**Issue by Rekyt** [frmunoz/ecolottery#4]
Following the documentation of  `coalesc()`:

> `theta` parameter of neutral dynamics in the regional pool (**used only if `pool=NULL`**), it is the “fundamental biodiversity number” (θ).

However the examples in `coalesc()` use theta even when the pool is defined:
https://github.com/frmunoz/ecolottery/blob/afb861d670526b28dd0f80d9bf5c65fef6fcaa23/pkg/man/coalesc.Rd#L103-L109

We should remove the use of `theta` in these cases.

**Comment by frmunoz** [comment]
You are right. I have changed these examples accordingly.
