### ISSUE TITLE
Documentation of limiting similarity in forward()

### ISSUE THREAD

**Issue by Rekyt** [frmunoz/ecolottery#7]
I am simulating communities using the `forward()` function with and without limiting similarity.

However I had to look into the code to get the precise formulation of limiting similarity in the model: https://github.com/frmunoz/ecolottery/blob/afb861d670526b28dd0f80d9bf5c65fef6fcaa23/pkg/R/forward.R#L460-L468
We could maybe add it somewhere in the documentation or in the vignette and let the user know that is uses a Gaussian function of the pairwise distance.

**Comment by frmunoz** [comment]
The new version of the forward allows passing a user-defined function of limiting similarity.
The default Gaussian function is explained, and the reference McArthur and Levins (1967) is included.
